"""empty message

Revision ID: 2525867213ca
Revises: 
Create Date: 2023-01-25 02:59:41.921552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2525867213ca"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "MODERATOR", "ADMINISTRATOR", name="role"),
            nullable=True,
        ),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("topped_up", sa.Float(), nullable=True),
        sa.Column("update_date", sa.DateTime(), nullable=True),
        sa.Column("registration_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("transactions")
    # ### end Alembic commands ###
