"""empty message

Revision ID: fbce700821ee
Revises: 9a6a1b581356
Create Date: 2023-03-15 02:39:53.068616

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fbce700821ee"
down_revision = "9a6a1b581356"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
